wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    bargraph:
      enabled: true
      graphIcon: "👿"
      graphStars: 25
      position:
        top: 3
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      updateInterval: 15
